version: 0.2

env:
  variables:
    APP_SRC: "src"
    MODULES_DIR: "vendored"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Installing dependencies...
      - yum groupinstall -y "Development Tools"``
      - yum -y install gcc openssl openssl-devel libffi libffi-devel python-devel gmp-devel
      - pip install --upgrade pip setuptools
  build:
    commands:
      - echo Entered the build phase...
      - pip install -t src/vendored/ -r src/requirements.txt
  post_build:
    commands:
      - echo Entered the post_build phase...
      - rm src/requirements.txt
      - aws cloudformation package --template-file sam.yaml --s3-bucket airdev-sean-artifact-repo --output-template-file output-sam.yaml
artifacts:
  files:
    - sam.yaml
    - output-sam.yaml
