AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Uploads file from S3 to an SFTP server
Resources:
  S3toSFTPWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3tosftp-worker
      Handler: s3tosftp-worker.lambda_handler
      Runtime: python2.7
      CodeUri: ./src

      AutoPublishAlias: dev

      DeploymentPreference:
       Type: AllAtOnce
       Alarms:
         # A list of alarms that you want to monitor
         - !Ref AliasErrorMetricGreaterThanZeroAlarm
         - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
